drop table BUY CASCADE CONSTRAINTS;
drop sequence BUY_SEQ;

create table BUY(
	BUY_ID			NUMBER, 
	CLASS_ID         NUMBER,
	MEMBER_ID      VARCHAR2(10),
	BUY_DATE		DATE NOT NULL, 
	PRIMARY KEY(CLASS_ID, MEMBER_ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);
create sequence BUY_SEQ;

select * from BUY;