drop table CLASS_REVIEW CASCADE CONSTRAINTS;
drop sequence CLASS_REVIEW_SEQ;

create table CLASS_REVIEW(
	REVIEW_ID			NUMBER,
	CLASS_ID			NUMBER NOT NULL,
	MEMBER_ID      		VARCHAR2(10) NOT NULL,
	REVIEW_CONTENT		LONG NOT NULL,
	REVIEW_STAR			NUMBER NOT NULL,
	REVIEW_DATE			DATE default sysdate,
	PRIMARY KEY(REVIEW_ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

create sequence CLASS_REVIEW_SEQ;

insert into CLASS_REVIEW
values(CLASS_REVIEW_SEQ.nextval, 1, 'A1111', '아주 재미있었어요!!', 0, sysdate);
insert into CLASS_REVIEW
values(CLASS_REVIEW_SEQ.nextval, 1, 'A2222', '즐거운 데이트였어요', 0, sysdate);

select * from CLASS_REVIEW;