drop table CLOVE CASCADE CONSTRAINTS;

create table CLOVE(
	CLASS_ID         NUMBER,
	MEMBER_ID      VARCHAR2(10),
	PRIMARY KEY(CLASS_ID, MEMBER_ID),
	FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);
		
select * from CLOVE;