drop table RECIPE_REVIEW CASCADE CONSTRAINTS;
drop sequence RECIPE_REVIEW_SEQ;

create table RECIPE_REVIEW(
	REVIEW_ID			NUMBER,
	RECIPE_ID			NUMBER NOT NULL,
	MEMBER_ID      		VARCHAR2(10) NOT NULL,
	REVIEW_CONTENT		LONG NOT NULL,
	REVIEW_STAR			NUMBER NOT NULL,
	REVIEW_DATE			DATE default sysdate,
	PRIMARY KEY(REVIEW_ID),
	FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

create sequence RECIPE_REVIEW_SEQ;

insert into RECIPE_REVIEW
values(RECIPE_REVIEW_SEQ.nextval, 1, 'A1111', '아주 맛있어요!!', 5, sysdate);
insert into RECIPE_REVIEW
values(RECIPE_REVIEW_SEQ.nextval, 1, 'A2222', '굴소스를 조금 덜 넣으면 더 맛있어요', 4, sysdate);

select * from RECIPE_REVIEW;