drop table SCRAP CASCADE CONSTRAINTS;

create table SCRAP(
	RECIPE_ID         NUMBER,
	MEMBER_ID      VARCHAR2(10),
	PRIMARY KEY(RECIPE_ID, MEMBER_ID),
	FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);
		
select * from SCRAP;